{"timestamp":"2025-07-27T12:42:19.871887","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-27T12:42:19.872264","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/__pycache__/nyc_trip_etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-27T12:42:19.895608Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T12:42:19.896215Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T12:42:19.896347Z","level":"info","event":"Current task name:load_csv_to_postgres","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T12:42:19.896508Z","level":"info","event":"Dag name:nyc_trip_etl","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T12:42:19.898088","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"postgres\" (172.18.0.2), port 5432 failed: FATAL:  database \"nyc_trips\" does not exist\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/scripts/load_csv_to_postgres.py","lineno":16,"name":"load_csv_to_postgres"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-27T12:42:19.912576Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T12:42:19.914576Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T12:42:19.915375Z","level":"info","event":"Task:<Task(PythonOperator): load_csv_to_postgres>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T12:42:19.916508Z","level":"info","event":"Failure caused by connection to server at \"postgres\" (172.18.0.2), port 5432 failed: FATAL:  database \"nyc_trips\" does not exist","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-27T12:42:19.917464Z","level":"info","event":"","chan":"stdout","logger":"task"}
